# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: external-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:sDUttIURHeHyc6RBz+ywGJ7wf/FOhEbvzN9DtJrPX1e1KAJYLf+TwQ==,iv:plFWbxOy4yLS2wjX/JT1bNs9VQ98l2OQVSauvC7NjNk=,tag:+L4o/t7NTFUB1nspqGC+CA==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1zk0r4lsnchfq0shn2kqevg85x4zrvyjzkq4acnrj9a7sgghvja9sas8vgz
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGNFZpS1dxS3BLbWpOaEFI
        VS9mTWpYVVZyMDY0anRQdHFSd2tPQnp0Q0ZNCmplQkhvcjhITVRWazlLQ2dqaFgr
        MjlIb1FUanJzeW1oYStlWXNPbHN4S0kKLS0tIG1MNkdBNWMvTzdnMjdoQmc3U0xa
        Qnc5RFo4N3FSaHBKTUhpK3dKRU5VZ0UKG+P4xpM9grKdZmTCFu/xaXxDX6A8yxKi
        XuJuc1vo9okfDJ5AksuWImfYbTxPqNddPm6NeZbzahTQUZp4GMxlAQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-26T14:35:32Z"
  mac: ENC[AES256_GCM,data:79LpVQ/aoJdEZ9C+XnJUADzdA4+8Vf7l03QFF7r9pRnABC8F3BCLKIvizqbki84LQ3TQaaY3uK9Y4Q7uxdpRBoYgiOj3Au+Qlq3SR9UOE1R9syrsCxQps1PZKIH0tPd7YGkfvXAJi8Vpdh6LnCJsDwUCsZ8Kr9Zw7ly0rH+KcqI=,iv:005ja0ZL9Cypaf/EeKzF7a1s721MyamfyVwxJwm6gmQ=,tag:E7IcCweR9FVFCPqoLazxfQ==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
