# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:q9nZ1SxrcpWuMdakmXVI+Cx+ULFJeJ4f6z71w69fsWk=,iv:GQhuWX8r8mUCQv8E/BteCQx9isd0n6tHjagHM4jeLT0=,tag:TIqAXQq1LTsQ5XnNvIde5w==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1zk0r4lsnchfq0shn2kqevg85x4zrvyjzkq4acnrj9a7sgghvja9sas8vgz
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjWXNLTWp6bmR4ck5LOGUx
        bFU0NFdaVUQrbEk4WGY1RXJlQ3ZkTkVvZ1E4Ci96WmlDeFp0U2tCREUyeEZHejNq
        am9BZ2Rsd2paZVJ6MVFzWmp0ZVJtancKLS0tIC9PYXNTTE5vZU1GWGZWeGw3d3ZU
        K1YxQXdldksrQStjajUxaWloSStBQUkK1leYyIipJ0RIzvmnjAf3pQSReNarDEll
        s1kKsYtV8lOdvf9JksYqV3eLNwiSyvZ/+yuyl7GtmaJjl/X/66x/yw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-26T14:35:32Z"
  mac: ENC[AES256_GCM,data:DOQI5v7KbA5K445CiSjQph2mzdSPpx5zVkVl9PQuvnAbXrM21aK2CGjqYTYJX19JkSJh5kw4NBxbHoD/IDr2qVFJCOmeVjhFdzNOPB2N/mnCS+xEQr+Ob/UzkTJj6QGTLC6L0iLXMANWiDBviUU9LiRC+fbxD07yaWx/Upxt/eY=,iv:bYSAbnCMMUO9Ix/FLddGaeT0lZl7oiNVIoj8PYi8mdQ=,tag:P9Eh6h3ojZkqiOKyUxGDmA==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
