# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:ZKJF3aHtrDZy9OJs5xZp62DGxu3wFJMsBCTl9J1Qjvo=,iv:WepSIWD2ejVqRWRMFDWEletsmJ4Wz01briID40s1DGQ=,tag:y/HcXHPi5es8yaxLpIxpdQ==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1zk0r4lsnchfq0shn2kqevg85x4zrvyjzkq4acnrj9a7sgghvja9sas8vgz
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3RVRYM0MySmxzcy9zYUJ2
        SnFRaC9VU0daMXI1VUFERHN6ckxkR0Vyc0RrCmZUd3NZNHF6RGJ1Q2JlM21pZUs1
        ZmhrbSt4TDNIMmFzazBObzZ0QUhVOWcKLS0tIGMvK2U2L285a21tQnc3U3haQSta
        dVhTVElLSnk4R2dCMXcvTWJ5MEVSTmcKAB7hllFMQ/fqE4gBFStmKw9XCTMyjXM2
        0G8NhYIPhLTo1XBrz5BzJbfJibxn7Ul8+dAV8TgmOzg8WDuxwNskCQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-28T13:01:20Z"
  mac: ENC[AES256_GCM,data:KsznqKdQGC4yKAVLhsonTq2KPKaRUlvfvA64uKySa5jGnRnCOV2gRhOypsx3jHmu4GLYZQtK1oDMNs2FaWsfJRVCDRScI9FUjac3Jf0/aG6thnWOlA/A5pfZ+QjcgC5gwFLyliH9XP8E9z+42aAKqjilH+4wguwBPKdK2dsJqR8=,iv:8DBoDvHVofvWnUbUKyQAzXj5YZZp+Ia4iK07ZPpUmns=,tag:qcVLawk+a3F3d35wo4USUQ==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
