apiVersion: v1
kind: Secret
metadata:
  name: sops-age
stringData:
  age.agekey: ENC[AES256_GCM,data:W63ZJtRGHSZ2JzrDfvbTTM2tqiF/HXxHvUqjOPjNjRk+kyapZEa0cNRl2SQch+YtaqFHiJ3BiSVEXJHit7I6mlKm0kewY7GCNyY=,iv:OfJ7yQB2k56RWhyzUPfjSqrtI66+LbF2iMEJPyoR+7k=,tag:AWxcQX9bD4v0240atGoULA==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1zk0r4lsnchfq0shn2kqevg85x4zrvyjzkq4acnrj9a7sgghvja9sas8vgz
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6elJWUzY5MG5FK2piM0Ns
        WE5UNHpuNEFqSDFtMUFOTEUvUG1SNnQvbHdFCnFiKzRFd1htdjA0YWp0ZTZheWxh
        QytKM05iY0lTYjlqNmhVNTRVcFZ4M3cKLS0tIFhoNG5LOThJcHRqaitzMlNhcXpO
        YTNrSEZwM3YwclFqdk1HZC9Gd01wTEkKdu9gBF4YeKDs9dj2HWvQg1e+pcxMt6P+
        WI4Hq9sgGC2coMM6R4384JPUfLXqEtxkVjvCb3t0ZD61V5o49C8G3w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-28T13:01:21Z"
  mac: ENC[AES256_GCM,data:TJzpZNEwM3+YW5XOkJVPvi1RZs7SdzpgMpEiMmja61kLuqNA/RhUH0+H3h25dR/Qfql5gYvuoOnUynAv50ooKRLrr3mfEOCBslXNaw+aRhUr6q/z0YDm6HFK2HWqVI1NIHifZktha9XgA1rPhsmX33L3jYNNPr8ATkso4yMpHVo=,iv:AVkOsPw7kz2PwS/o4aObl3Jo1ExRZm6XfIYP7YYSi0M=,tag:VPZCiRCosUzUVYDNDTgxtQ==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
